version: '3.7'

services:
  app:
    container_name: api-patinhas-admin
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    entrypoint: dockerize -wait tcp://patinhasDb:5432 -timeout 20s sh -c npm install && tail -f /dev/null
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .:/home/node/app
    depends_on:
     - patinhasDb
    networks:
      - net-admin
  patinhasDb:
    image: postgres
    container_name: patinhasDb
    restart: always
    networks:
      - net-admin
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=patinhasAdminDb

# networks:
#   default:
#     name: patinhas-ntw
#     external: true

# networks:
#   patinhas-ntw:
#     external: true
networks:
  net-admin:
    name: net-admin
    driver: bridge