from node:16.16.0-slim


USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .

RUN npm install --location=global npm@8.19.2

RUN npm install

RUN npm run build

CMD ["npm", "run", "start:prod"]
